cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.jdk"
sudo: false
env:
  global:
  - TARGET=install
  - JDKW=https://raw.githubusercontent.com/vjkoskela/jdk-wrapper/master/jdk-wrapper.sh
  - secure: "cp4GRqZaBPeg7JSGYDdUuJLMuLznNb8DspNc4V/ukM+CMkgvXGz2m2iER/zxv6rZuonDEFEJ3A8T4NAmfPKh/FBjUkT/1TZcXbUHCs3aEBowTJDkBkucZUlyDhsf9r2kaaUqiscowokjjnfeEhNdwFhK51qjrzYq1I3di3CWO0Lve8Asywot7a+fYaOs0GW4DaFSLNBuXeVE3aoaMglZh/OZm8Cf6AMlDyH8glS2nVLwuW1zv7/UyHzhhjD/oA3eqQRNrCRlVBycKN1SJcP5FTooaluZ53eUjzt32HbYlMJwhQA2C7YQHJwA75AG+RO0e8nkbxjAQvQexA0cZqWw/bEmWl1SEbHoejTHKBmVAyNpYSCnC5pF0bgiocZtWpS1zaDixER8rIkDBVrsiztcvxD3nOPqQoKXTSrsIyDeiErFoTrIWKrug2trtxXnDwsp5cXosnibZpbLHVcCkx27E8aYaorn9hFp+wTig1H6Towh+LtaTTIKUqPIb4BIwRxAq2YaESO2kmlt8a9VA1JCdE6i7f82okBlo2ROBlIE7jssbeTAMcaC+VGQPM67OREJ9gSetl67ncEGin54iN05xwT87CDEu3Rg8yG/PJPBn5FzL5yPL98iHnyXesdGcngAGf0P8JrtTThFZs2PzdYuPezOt0TohrBud40xg/0jD2w="
  - secure: "AMTGDWmQ/2bhKB9Je4CuhP32XUOzl2vYs/IPvHsjYaUMLB/slhjeljBFLB1eURqR3tZPDNCOA+9TfwUIQJnK1hGNGYxkHPOKC6PN66PawLThzSLxiSKecdMriOMpdeubAO1C3YLlHIO8awt2aCDLE25oDQYScUSSwYEaUIK0JL0sP6LWkVAPCjcBXy2U1BRUHHovIDw8dNNbusUjPbctfHNy+gJPkP6Q8aZs5kfELeXsUq1xfKugxWT0zWW3dE1xr9hhUCv8JBHIuib4pv7HrqGPHLFqTL4LgkrWurabWe4NPcj1wWcrNz8TvU3npt2DjIjqKD8HoO5t0R01ocvn4rUZwJGuO2/vOgSP05VqECqVUgiU2PIO/f4bM4QPfOva/bI/gIjlrljol9b0EzVKFRE/oAXogAvzMH6yDu6F5ABWe2WMZtTl6ja3gPSn31kOu9k5lVlCyhzdniFbxDX/a7zCTbm1E6DMTqu6X3NUkiyM6/Ec8gVSun8Gsos8ZnCY0zwsjUUpjUogFTMwWO10VhgMwDldWBAOQR93BIb6NYZxYmAj3xM5Rg6S4vIEsxWP5eLdLgf/3s6Xbrhlmx4jOTHpx7jI3usMmVhctKblIULEn6GND08ZEOdjQ7MhJAfUgkbED4C77LFXiLyCRYlQYt/l7ox28hq245BuJRhGivU="
install: true
before_script:
- gpg --import ism.key
- if [ \( -n "${TRAVIS_TAG}" \) -a  "${TRAVIS_PULL_REQUEST}" = "false" ]; then export TARGET="deploy -P release --settings settings.xml"; fi;
script:
- curl -s ${JDKW} | bash /dev/stdin ./mvnw clean ${TARGET} -U
